'use strict';
// Форма window.api: единый список для сетевого моста. Сверяется с preload.js
// тестом ниже — расхождение означает метод, который в браузере просто
// отсутствует и падает в неожиданный момент, а не при загрузке.
export const API_SHAPE = {
  'config.get': { channel: 'config:get', kind: 'invoke' },
  'config.set': { channel: 'config:set', kind: 'invoke' },
  'tabs.open': { channel: 'tabs:open', kind: 'invoke' },
  'tabs.close': { channel: 'tabs:close', kind: 'invoke' },
  'tabs.chooseFolder': { channel: 'tabs:chooseFolder', kind: 'invoke' },
  'tabs.markSeen': { channel: 'tabs:seen', kind: 'send' },
  'term.start': { channel: 'term:start', kind: 'send' },
  'term.write': { channel: 'term:write', kind: 'send' },
  'term.resize': { channel: 'term:resize', kind: 'send' },
  'term.restart': { channel: 'term:restart', kind: 'send' },
  'term.onData': { channel: 'term:data', kind: 'event' },
  'term.onExit': { channel: 'term:exit', kind: 'event' },
  'term.onStarted': { channel: 'term:started', kind: 'event' },
  'shell.openExternal': { channel: 'shell:openExternal', kind: 'invoke' },
  'app.onNotice': { channel: 'app:notice', kind: 'event' },
  'app.devtools': { channel: 'app:devtools', kind: 'invoke' },
  'project.connect': { channel: 'project:connect', kind: 'invoke' },
  'project.status': { channel: 'project:status', kind: 'invoke' },
  'git.get': { channel: 'git:get', kind: 'invoke' },
  'git.onChanged': { channel: 'git:changed', kind: 'event' },
  'gh.repo': { channel: 'gh:repo', kind: 'invoke' },
  'gh.global': { channel: 'gh:global', kind: 'invoke' },
  'tab.onStatus': { channel: 'tab:status', kind: 'event' },
  'tab.onActivate': { channel: 'tab:activate', kind: 'event' },
  'workspace.get': { channel: 'workspace:get', kind: 'invoke' },
  'workspace.setActive': { channel: 'workspace:setActive', kind: 'send' },
  'workspace.ready': { channel: 'workspace:ready', kind: 'send' },
  'ghost.save': { channel: 'ghost:save', kind: 'invoke' },
  'ghost.load': { channel: 'ghost:load', kind: 'invoke' },
  'attention.update': { channel: 'attention:update', kind: 'send' },
  'screenshot.paste': { channel: 'screenshot:paste', kind: 'invoke' },
  'queue.add': { channel: 'queue:add', kind: 'send' },
  'queue.remove': { channel: 'queue:remove', kind: 'send' },
  'queue.clear': { channel: 'queue:clear', kind: 'send' },
  'queue.onChanged': { channel: 'queue:changed', kind: 'event' },
  'history.search': { channel: 'history:search', kind: 'invoke' },
  'history.refresh': { channel: 'history:refresh', kind: 'invoke' },
  'recipes.list': { channel: 'recipes:list', kind: 'invoke' },
  'recipes.savePrompt': { channel: 'recipes:savePrompt', kind: 'invoke' },
  'recipes.deletePrompt': { channel: 'recipes:deletePrompt', kind: 'invoke' },
  'recipes.fillPrompt': { channel: 'recipes:fillPrompt', kind: 'invoke' },
  'recipes.normalizeForPty': { channel: 'recipes:normalizeForPty', kind: 'invoke' },
  'recipes.listWorkspaces': { channel: 'recipes:listWorkspaces', kind: 'invoke' },
  'recipes.saveWorkspace': { channel: 'recipes:saveWorkspace', kind: 'invoke' },
  'recipes.deleteWorkspace': { channel: 'recipes:deleteWorkspace', kind: 'invoke' },
  'night.toggle': { channel: 'night:toggle', kind: 'invoke' },
  'night.get': { channel: 'night:get', kind: 'invoke' },
  'night.onChanged': { channel: 'night:changed', kind: 'event' },
  'usage.get': { channel: 'usage:get', kind: 'invoke' },
  'usage.refresh': { channel: 'usage:refresh', kind: 'invoke' },
  'usage.onUpdate': { channel: 'usage:update', kind: 'event' },
  'stt.transcribe': { channel: 'stt:transcribe', kind: 'invoke' },
  'stt.status': { channel: 'stt:status', kind: 'invoke' },
};
